version: '2'
services:
  app:
    build: app/
    image: chuross/react-lgtm-app
    container_name: react-lgtm-app
    ports:
      - 8080:8080
  server:
    build: server/
    image: chuross/react-lgtm-server
    container_name: react-lgtm-server
  mongo:
    image: mongo
