version: '2'
services:
  front:
    build: app/
    image: chuross/react-lgtm-front
    container_name: react-lgtm-front
    ports:
      - 8080:8080
  api:
    build: api/
    image: chuross/react-lgtm-api
    container_name: react-lgtm-api
    links:
      - react-lgtm-mongo:mongo
  mongo:
    image: tutum/mongodb
    container_name: react-lgtm-mongo
    environment:
      AUTH: no
